/* Auto-generated by genmsg_cpp for file /home/lucid/ros/stacks/ccny-ros-pkg/asctec_drivers/asctec_msgs/msg/Height.msg */
#ifndef ASCTEC_MSGS_MESSAGE_HEIGHT_H
#define ASCTEC_MSGS_MESSAGE_HEIGHT_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "roslib/Header.h"

namespace asctec_msgs
{
template <class ContainerAllocator>
struct Height_ : public ros::Message
{
  typedef Height_<ContainerAllocator> Type;

  Height_()
  : header()
  , height(0.0)
  , height_variance(0.0)
  {
  }

  Height_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , height(0.0)
  , height_variance(0.0)
  {
  }

  typedef  ::roslib::Header_<ContainerAllocator>  _header_type;
   ::roslib::Header_<ContainerAllocator>  header;

  typedef double _height_type;
  double height;

  typedef double _height_variance_type;
  double height_variance;


private:
  static const char* __s_getDataType_() { return "asctec_msgs/Height"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROSCPP_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "4294dcd372c9dbcff581cfdfeb67fc9e"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROSCPP_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
\n\
float64 height\n\
float64 height_variance\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROSCPP_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROSCPP_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, height);
    ros::serialization::serialize(stream, height_variance);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, height);
    ros::serialization::deserialize(stream, height_variance);
    return stream.getData();
  }

  ROSCPP_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(height);
    size += ros::serialization::serializationLength(height_variance);
    return size;
  }

  typedef boost::shared_ptr< ::asctec_msgs::Height_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asctec_msgs::Height_<ContainerAllocator>  const> ConstPtr;
}; // struct Height
typedef  ::asctec_msgs::Height_<std::allocator<void> > Height;

typedef boost::shared_ptr< ::asctec_msgs::Height> HeightPtr;
typedef boost::shared_ptr< ::asctec_msgs::Height const> HeightConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::asctec_msgs::Height_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::asctec_msgs::Height_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace asctec_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::asctec_msgs::Height_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4294dcd372c9dbcff581cfdfeb67fc9e";
  }

  static const char* value(const  ::asctec_msgs::Height_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4294dcd372c9dbcfULL;
  static const uint64_t static_value2 = 0xf581cfdfeb67fc9eULL;
};

template<class ContainerAllocator>
struct DataType< ::asctec_msgs::Height_<ContainerAllocator> > {
  static const char* value() 
  {
    return "asctec_msgs/Height";
  }

  static const char* value(const  ::asctec_msgs::Height_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::asctec_msgs::Height_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
\n\
float64 height\n\
float64 height_variance\n\
\n\
================================================================================\n\
MSG: roslib/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::asctec_msgs::Height_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::asctec_msgs::Height_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::asctec_msgs::Height_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.height);
    stream.next(m.height_variance);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Height_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asctec_msgs::Height_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::asctec_msgs::Height_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::roslib::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "height_variance: ";
    Printer<double>::stream(s, indent + "  ", v.height_variance);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ASCTEC_MSGS_MESSAGE_HEIGHT_H

